### ISSUE TITLE
suffermore error missing opcodes

### ISSUE THREAD

**Issue by Gradnos** [akusei/suffer2gether#3]
i find Assembly-CSharp.dll manually from browse and select it and after I press patch it says "suffermore error missing opcodes"
i don't know what to do, I might have installed this wrong somehow?

**Comment by akusei** [comment]
Thanks for reporting this. I have a couple questions that will help me troubleshoot this.

1. Where did you get your copy of Green Hell?
2. What version of the game are you running?

**Comment by akusei** [comment]
Also, what is the path to the assembly-csharp.dll file you were using? This can happen if you accidentally choose the wrong unity3d game

**Comment by akusei** [comment]
Did you get this figured out @Gradnos ?

**Comment by akusei** [comment]
Closing this as a non-issue since the OP has not responded. Most likely this was the incorrect assembly-csharp.dll file for a different unity game. @Gradnos feel free to open a new issue if you encounter this again
